### ISSUE TITLE
Plant Death

### ISSUE THREAD

**Issue by sensible-heart** [DaynaLacoursiere/MandalaGame#2]
The plants that you have added to your mandala should only exist on ring for 30-45 seconds.
After 30-45 seconds the plants should disappear.
They are not clicked to delete.
Ideally the amount of time before the plant ring disappears is random.
- [ ] #3   Plant Death Animation

**Comment by DaynaLacoursiere** [comment]
Commit 98b6dbccfbc8ed93aaccc8124c87765c0e284247 closes this issue. (Accidentally closed #3 instead)
