### ISSUE TITLE
Plant Death Animation

### ISSUE THREAD

**Issue by sensible-heart** [DaynaLacoursiere/MandalaGame#3]
When the plants disappear after 30-45 seconds, they must disappear with an animation rather than blinking out of existence.
This can be a fade out animation or shrinking the plant into non-existence depending on how they look.

Linked to:
#17 Creating Fade Animations for Each Plant

**Comment by DaynaLacoursiere** [comment]
Accidentally closed the wrong one

**Comment by DaynaLacoursiere** [comment]
I think closing #17 also closes this. So...

**Comment by sensible-heart** [comment]
Yep as long as every plant object has an assigned fade sprite in its create
function. Then it's done.
