### ISSUE TITLE
Clicking on a Plant Allows Its Rotation

### ISSUE THREAD

**Issue by sensible-heart** [DaynaLacoursiere/MandalaGame#8]
When you click on a plant, it should allow you to rotate the plant and all of it's copies in the ring. 
The rotation is oriented to the mouse pointer.

Linked:
#9 Second Click on Plant

**Comment by sensible-heart** [comment]
This will be super helpful.
https://docs.yoyogames.com/source/dadiospice/002_reference/objects%20and%20instances/instances/instance%20properties/image_angle.html

**Comment by DaynaLacoursiere** [comment]
Keep in mind that you can't orient something with a mouse in this way. A mouse knows _where_ it is, but it doesn't know it's orientation. 

Alternatively, when you click on a plant, the game could pause and the plant could rotate as you move the mouse (https://zero.digipen.edu/_images/FinalLookAt1.gif) and then a second click would both play the game and attach the plant
